# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'


# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

# Cocoapods binary
plugin 'cocoapods-binary'

# Keep source code for backing up
keep_source_code_for_prebuilt_frameworks!

# Enable bitcode
enable_bitcode_for_prebuilt_frameworks!

# Apply prebuilt for all pods
all_binary!

target 'TestEndpoint' do
  
  # Pods for TestEndpoint
  pod 'Alamofire', '4.9.1'
  pod 'AlamofireNetworkActivityIndicator', '2.4.0'
  pod 'Eureka', '5.3.2'
  pod 'SwiftyJSON', '5.0.0'
  pod 'IQKeyboardManagerSwift', '6.1.1'
  pod 'SVProgressHUD', '2.2.5'
  pod 'SnapKit', '4.2.0'
  pod 'STPopup', '1.8.7'
  pod 'FontAwesomeKit', '2.2.1'
  pod 'NumPad', '3.0.1'
  pod 'DeviceKit', '~> 1.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['DEBUG_INFORMATION_FORMAT[sdk=iphoneos*]'] = 'dwarf-with-dsym'
        config.build_settings['DEBUG_INFORMATION_FORMAT[sdk=iphonesimulator*]'] = 'dwarf'
      end
    end
  end
end
